server:
  port: 8000

pangaea:
  notify-topic:
    name: topic1
     
spring:
  kafka:
    producer:
       bootstrap-servers: localhost:29092
       key-serializer: org.apache.kafka.common.serialization.StringSerializer
       value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
       request-timeout-ms: 2000
       max-request-size: 26214400
       enable-idempotence: true
       retries: 2147483647
       max-in-flight-requests-per-connection: 5
       acks: all
       transaction-timeout-ms: 900000
    consumer:
       bootstrap-servers: localhost:29092
       key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
       value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
       auto-offset-reset: earliest
       max-partition-fetch-bytes: 1048576
       max-poll-interval-ms: 300000
       max-poll-records: 500
       heartbeat-interval-ms: 3000
       session-timeout-ms: 10000
       fetch-max-wait-ms: 500
       fetch-min-bytes: 16384
       enable-auto-commit: false
       auto-commit-interval-ms: 1000
       isolation-level: read_committed
          
