---
version: '3.4'
services:
  zookeeper:
   image: confluentinc/cp-zookeeper:6.1.0
   hostname: zookeeper
   container_name: zookeeper
   restart: unless-stopped
   volumes:
      - ./kafka/zookeeper/secrets/:/opt/zookeeper/secrets
   networks:
      - kafka-network
   ports:
      - "2181:2181"
   environment:
     ZOOKEEPER_CLIENT_PORT: 2181
     ZOOKEEPER_TICK_TIME: 2000
     
  broker:
   image: confluentinc/cp-kafka:6.1.0
   hostname: broker
   container_name: broker
   volumes:
      - ./kafka/broker/secrets/:/opt/kafka/secrets
   restart: unless-stopped
   depends_on:
      - zookeeper
   networks:
      - kafka-network
   ports:
      - "29092:29092"
   environment:
     KAFKA_BROKER_ID: 1
     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, INTERNAL_HOST:PLAINTEXT
     KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:9092, INTERNAL_HOST://localhost:29092
     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
     KAFKA_JMX_PORT: 9101
     KAFKA_LOG4J_LOGGERS: "kafka.autorizer.logger=INFO"
     KAFKA_LOG4J_ROOT_LOGLEVEL: INFO

networks:
 kafka-network:
   name: notification-kafka-network
   driver: bridge

      